### ISSUE TITLE
Implement removeHeader on response

### ISSUE THREAD

**Issue by daliwali** [uNetworking/bindings#11]
Is this possible to do actually? Currently only `setHeader` and `getHeader` are implemented.

**Comment by alexhultman** [comment]
Imo appendHeader is the only sane function and the only thing a dev should need. Sadly Node.js disagrees.

**Comment by daliwali** [comment]
I see. I went ahead and monkey-patched an existing implementation that relied on Node.js `http` to work in the same way. Also did a workaround for reading headers outside of the request listener (I guess headers are freed after this point?)

https://github.com/fortunejs/fortune-http/blob/0d7eda0e1e583218aa5bd34d6615c02d461ae4f5/lib/index.js#L162-L182

**Comment by alexhultman** [comment]
The idea is that you only need to read headers in the event handler (if you need a particular value you copy that value) then you respond by appendHeader and end. Very simple, very minimal and is everything you need really. Node.js has a completely different design where things are built in the least efficient way possible - why support removing a header? It is like supporting removing already committed data in a stream. No, the dev has to not be brain dead and instead *not add headers that shouldn't be added*.
