### ISSUE TITLE
uws http doesn't set header

### ISSUE THREAD

**Issue by hbakhtiyor** [uNetworking/bindings#21]
e.g.

```js
const http = require("uws").http;

http.createServer((req, res) => {
	res.setHeader('Connection', 'close');
	res.end('Hello World!');
}).listen(8000);
```
`$ curl -I localhost:8000`

results
```
HTTP/1.1 200 OK
Content-Length: 12
```

**Comment by daliwali** [comment]
I ran into this problem as well. The workaround is to use `writeHead` instead.

**Comment by hbakhtiyor** [comment]
@daliwali thanks, why not to do api compatibility with node http api core?

**Comment by hbakhtiyor** [comment]
the same code with `writeHead` instead of `setHeader`, returning 

`$ curl -I localhost:8000`

```
HTTP/1.1 0 close
```

for `HEAD\GET` requests

`0` instead of `200` status code and without `content-length` header

**Comment by alexhultman** [comment]
#17
