### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary (Node.js 8.0.0 / Windows 10.0.15063 x64)

### ISSUE THREAD

**Issue by kyrylkov** [uNetworking/bindings#24]
* Node.js 8.0.0
* Windows 10.0.15063 x64
* Visual Studio 2017
* VC++ 2017 v141 toolset

> Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'

**Comment by alexhultman** [comment]
What version of Visual C++ do you have?

**Comment by kyrylkov** [comment]
Visual Studio 2017 w/ VC++ 2017 v141 toolset

**Comment by alexhultman** [comment]
node_modules/uws/build_log, can you post this. I tried Node.js 8 on Linux and it worked. Hanven't tried on Windows.

**Comment by kyrylkov** [comment]
```
C:\Users\kyryl\dev\uws\node_modules\uws>if not defined npm_config_node_gyp (node "C:\Users\kyryl\AppData\Local\nvs\node\8.0.0\x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\kyryl\AppData\Local\nvs\node\8.0.0\x64\node_modules\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\kyryl\\AppData\\Local\\nvs\\default\\node.exe" "C:\\Users\\kyryl\\AppData\\Local\\nvs\\node\\8.0.0\\x64\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kyryl\dev\uws\node_modules\uws
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
```

**Comment by kyrylkov** [comment]
I suspect it doesn't like `VC++ 2017 v141 toolset`.  Installing `VC++ 2015.3 v140 toolset` to test.

**Comment by alexhultman** [comment]
Yeah something is wrong with the compiler set-up (or just node-gyp).

**Comment by kyrylkov** [comment]
node-gyp issue: https://github.com/nodejs/node-gyp/issues/1179#issuecomment-301217151

Please close.

**Comment by AnubisCode** [comment]
have same error with the compilation :(

- Windows 10 Version 1709 x64
- Visual Studio 2017
- Visual Studio C++ core features
- VC++ 2017 v141 toolset
- Windows 10 SDK 10.0.14393.0 
- Universal CRT SDK
all these are installed..

**Comment by CoolHandLuke88** [comment]
I ran into this exact issue.
I wanted to leave this here for anyone else that may run into this issue with docker and `uws` installation.

Hope you guys don't mind I drop this here.

In Dockerfile
*********************************
`FROM node:8.9-alpine`

`RUN apk add --update \`
    `libc6-compat`

*********************************
Needed `libc6-compact`

This should resolve the issue seen below.

`Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.`
