### ISSUE TITLE
No pong method for WebSocket

### ISSUE THREAD

**Issue by Hersir88** [uNetworking/bindings#27]
Any reason why ping method is implemented but not pong for node js?

**Comment by alexhultman** [comment]
Ping is an action, pong is an event. You don't pong an endpoint, you ping it. It is possible to send a pong with the native-object though.

**Comment by Hersir88** [comment]
Ah ok, just java implementation what I use for android client is sending pings to server, wanted to replay to it and could not find pong method

**Comment by alexhultman** [comment]
All pings are automatically responded to with a pong. That is according to spec, you never need to manage that yourself.

**Comment by Hersir88** [comment]
Thank you for clarification, also will make issue on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/uws/index.d.ts as looks like there is pong method in types
