### ISSUE TITLE
on.close: how to get reference to the websocket being closed

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [uNetworking/bindings#28]
The **wsCloseHandler** gets only the code and the why a client decided to close its websocket.

Could it be possible to obtain a reference to the websocket being closed?

```
const wsCloseHandler = (code, reason) => {
  console.log(`wsCloseHandler: code=${code}, reason="${reason}"`);
};
```
```
ws.on('close', wsCloseHandler);
```

**Comment by alexhultman** [comment]
This is a general JavaScript programming question. I don't provide general programming help.
