### ISSUE TITLE
error Compilation of uWebSockets has failed and there is no-precomp.....

### ISSUE THREAD

**Issue by rivor2** [uNetworking/bindings#29]
Full error text: Compilation of µWebSockets has failed and there is no pre-compiled binary
 available for your system. Please install a supported C++11 compiler and reinst
all the module 'uws'.

Nodejs version 6.10.3 (windows)
OS: Windows 7 Ultimate 32bit

Note that NPM installation went successfully without any single error.
I tried even with this website https://npm.runkit.com/uws and it is doing same thing http://prntscr.com/fj71rj

Any solution for this?

**Comment by rivor2** [comment]
@alexhultman

**Comment by alexhultman** [comment]
C++ compiler version?

**Comment by rivor2** [comment]
@alexhultman i'm not sure if i have one, but i got Visual Studio 2017 installed, with no any additional packages. Not sure how to do with it tho. I just got started and friend of mine recommended uWS instead of socket.io.
