### ISSUE TITLE
Allow passing an optional callback to server.close()

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/bindings#3]
https://github.com/uWebSockets/uWebSockets/issues/447

**Comment by chintan39** [comment]
This is must have as we need to know when exactly all the connections are closed.

**Comment by chintan39** [comment]
Waiting for your updates on this issue

**Comment by alexhultman** [comment]
You could possibly start a timer of 20 seconds if you need to know when the server has forcibly closed

**Comment by chintan39** [comment]
That's how I am doing it right now, but can't be sure how much time will it take to close when there are thousands of connections

**Comment by alexhultman** [comment]
It takes 20 seconds.
