### ISSUE TITLE
node-gyp not included in package.json dependencies

### ISSUE THREAD

**Issue by jharris4** [uNetworking/bindings#31]
I've been trying to debug an issue with install `uws` with the yarn package manager.

https://github.com/yarnpkg/yarn/issues/3728

I just noticed that `node-gyp` is not listed as a dependency in `dist/package.json`.

I think that node-gyp should be listed as a dependency, something like:

```
"dependencies": {
    "node-gyp": "^3.3.1"
}
```

(Or perhaps semver `^4.0.0` if you want to use the latest version)

It seems to me that this should be included since the scripts entry has this:

```
"scripts": {
  "install": "node-gyp rebuild > build_log.txt 2>&1 || exit 0"
}
```

**Comment by jharris4** [comment]
Created a PR #32

**Comment by jharris4** [comment]
Some back story to this issue, it seems that Node 7 shipped with a bundled version of the `node-gyp` package, but Node 8 DOES NOT.

So adding the dependency is needed for specifically for Node 8.

**Comment by alexhultman** [comment]
There is no real dependency on node-gyp, it can run without it using the pre-compiled binaries. And if it is true Node has removed node-gyp then that's their problem. Besides, node-gyp is only a small fraction of what you really will need to have installed in order to compile anyways.

**Comment by ForsakenHarmony** [comment]
https://github.com/uNetworking/bindings/blob/master/nodejs/dist/package.json#L5

"No real dependency"

**Comment by alexhultman** [comment]
@ForsakenHarmony 
![](http://www.mypokecard.com/my/galery/695YaxVx7voy.jpg)

**Comment by efistokl** [comment]
@alexhultman It breaks creating of yarn.lock. https://github.com/yarnpkg/yarn/issues/3555 and https://github.com/socketio/engine.io/issues/516

**Comment by alexhultman** [comment]
Read the FAQ. I deploy to NPM for Node.js. If some third party then repackages my NPM package for another package manager, this is not my problem to solve. I don't care if you use Yarn or not, I only support NPM. You can either accept this or leave.

**Comment by STRML** [comment]
Not specifying `node-gyp` in your dependencies opens you up to breakage if node-gyp undergoes a major version. I agree that this is a yarn bug overall but it's good to lock down your deps.

**Comment by alexhultman** [comment]
node-gyp is a bloated piece of garbage project not good for anything. It is yet another build system, one of 6 trillion, completely redundant and worthless, accomplishing nothing at all. Python dependency, a whole pyramid of JS dependencies and all for what? Specifying g++ *.cpp. Report Yarn bugs elsewhere.

**Comment by alexhultman** [comment]
@efistokl No. Yarn breaks itself by **wrongly assuming** a dependency of node-gyp even though this is an **invalid fucking assumption**
