### ISSUE TITLE
Getting request information 

### ISSUE THREAD

**Issue by thomas-jeepe** [uNetworking/bindings#35]
For my application, I need to authenticate a user by getting a cookie from the request. If I was using `ws`, per the documentation I could do this to get the cookies.

```js
wss.on('connection', function connection(ws, req) {
  const location = url.parse(req.url, true);
  // You might use location.query.access_token to authenticate or share sessions
  // or req.headers.cookie (see http://stackoverflow.com/a/16395220/151312)

  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});
```

So, I tried logging the parameters passed to the connection handler:

```js
const server = new WebSocket.Server({ port: 3000 })
server.on('connection', (...args: any[]) => console.log(args))
```
Output:
```
[ WebSocket {
    external: [External],
    internalOnMessage: [Function: noop],
    internalOnClose: [Function: noop],
    onping: [Function: noop],
    onpong: [Function: noop] } ]
```
The only parameter passed is the websocket and not the request.
Then, how is one to get the request information? Should this be implemented in the connection handler to follow `ws` or some other way?

**Comment by lauriro** [comment]
I had same issue, fixed and I made a pull request

**Comment by jkuri** [comment]
you can get request information like so:
```js
wss.on('connection', ws => console.log(ws.upgradeReq));
```
