### ISSUE TITLE
Create TypeScript typings definitions for Node.js bindings project

### ISSUE THREAD

**Issue by ORESoftware** [uNetworking/bindings#36]
It would be great to have `@types/uws`, or TypeScript definitions in the Node.js bindings project.

**Comment by ORESoftware** [comment]
I was able to install `@types/uws`:

`─ @types/uws@0.13.0 `

but for some reason, the version for uws has jumped like version 8.14.0

how did that happen?

<img width="437" alt="screenshot 2017-07-02 14 22 12" src="https://user-images.githubusercontent.com/11139560/27773587-dd993804-5f31-11e7-885c-3ce61862c6de.png">

**Comment by abenhamdine** [comment]
AFAI 8.14.0 is the current version of uws bindings for node (this repo) while 0.14.5 is the current version of the core c++ lib (https://github.com/uNetworking/uWebSockets)
