### ISSUE TITLE
Nexe.js/libUV linux build segmentation fault

### ISSUE THREAD

**Issue by jdmnd** [uNetworking/bindings#39]
Hi there,

We are building uWS into a node.js binary using [nexe](https://github.com/nexe/nexe) and are attempting an upgrade from version 0.12 to 8.14.0.

The build as it is currently configured appears to build and run successfully on Windows and Darwin, but we're having trouble compiling on linux using `g++-4.8`. We've set the `USE_LIBUV` flag, and [tried to patch](https://github.com/deepstreamIO/deepstream.io/blob/1b129c58b6b223b9fd067a06b6c91ce4ce1efbf8/scripts/package.sh#L111) some naming conflicts with node, but while the build now completes, the following segmenation fault occurs on startup:
```
ubuntu@ip-172-31-22-230:~/dsio$ gdb ./deepstream
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
...
Program received signal SIGSEGV, Segmentation fault.
0x000000000131894a in uv_check_init (loop=0x1e60530, handle=0x1e59de0 <check>) at ../deps/uv/src/unix/loop-watcher.c:67
67      ../deps/uv/src/unix/loop-watcher.c: No such file or directory.
```
For context, the changes are in [this pull request](https://github.com/deepstreamIO/deepstream.io/pull/745) on the deepstream.io project, and the code relevant to the nexe build is in [https://github.com/deepstreamIO/deepstream.io/blob/1b129c58b6b223b9fd067a06b6c91ce4ce1efbf8/scripts/package.sh#L55](scripts/package.sh).

Any help would be much appreciated,
Thanks in advance!
John

**Comment by alexhultman** [comment]
You are including the wrong files in your build. Check this Makefile: https://github.com/uNetworking/bindings/blob/master/nodejs/Makefile#L1

And you are building an extension, not an addon so instead of addon.cpp you go with extension.cpp

**Comment by jdmnd** [comment]
Thanks @alexhultman 
I think I'm including the files you mention:
https://github.com/deepstreamIO/deepstream.io/blob/uws-14/scripts/package.sh#L97

Incase it's enlightening, here's a backtrace from the linux segfault:
```
#0  0x000000000131894a in uv_check_init (loop=0x1e5b0a0, handle=0x1e55d20 <check>) at ../deps/uv/src/unix/loop-watcher.c:67
#1  0x00000000010748d6 in node::Main(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>) ()
#2  0x000000000109c2f2 in node::Binding(v8::FunctionCallbackInfo<v8::Value> const&) ()
#3  0x0000000000958712 in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#4  0x00000000009b7a6e in v8::internal::(anonymous namespace)::HandleApiCallHelper(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)3>) ()
#5  0x00000000009b830e in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
```

**Comment by alexhultman** [comment]
Check again

**Comment by jdmnd** [comment]
Forgive my stupidity but I really don't see what I'm missing. 🤔
Could you be more specific?

**Comment by alexhultman** [comment]
Remove those SED replacements they are not solutions in fact they are the reason everything is broken in your build. By removing those errors via random hacks you hide the real reason behind this; "export USE_LIBUV" is not correct it needs to be "-DUSE_LIBUV" (as you can see in the Makefile). It is a gcc flag, not an environment variable.
