### ISSUE TITLE
_socket.remoteAddr format

### ISSUE THREAD

**Issue by ad34** [uNetworking/bindings#40]
When I reach a node.js application using uws from a c++ app using uwebsockets libs.

The _socket.removeAddress looks like this  

{
 remotePort : 61408,
 removeAddress   :  ":ffff:195.22.xx.xx",
 removeFamily : "IPv6"

}

it looks like an ipv4 with some ffff at the beginning.

any reason for this ? I found that this ip is an ip from a router of my company. but the strange thing is that it s not the same ip I got if I just a simple PHP script on the same server displaying the remote address.

**Comment by alexhultman** [comment]
It is an IPv6 address as given to you by the kernel.
