### ISSUE TITLE
Node: Don't create build_log.txt

### ISSUE THREAD

**Issue by laino** [uNetworking/bindings#49]
Please don't redirect output to ```build_log.txt``` in ```$PWD``` and instead let me use my own logging if I need to.
Just blindly redirecting output to ```build_log.txt``` breaks the build in my build environment:

```
> uws@0.14.5 install [redacted]/app/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied
sh: 1: node-gyp: Permission denied
```

Offending line:
 https://github.com/uNetworking/bindings/blob/c90322386578c5c4de8e833c10ef9383438920a5/nodejs/dist/package.json#L5

**Comment by laino** [comment]
Turns out it wasn't the cause, but still please don't do it ;_;

**Comment by abhibaba97** [comment]
can you tell me, how did you resolve this problem
