### ISSUE TITLE
Can't install uws npm package

### ISSUE THREAD

**Issue by okaufmann** [uNetworking/bindings#53]
Hi, 

I'd like to use uws in my nodejs socket.io server. But if I install uws I get an error:
```
cannot create build_log.txt: Permission denied
```

If I try to require uws anyway, I get the following error as more or less expected:
```
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (/usr/lib/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/usr/lib/node_modules/uws/uws.js:42:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at repl:1:1
```

I've installed all the required build tools (as described here: https://github.com/uNetworking/uWebSockets#getting-started) and run the following command:
```
sudo apt-get install openssl zlib1g-dev libuv1
```

I've tried this on a Ubuntu 16.04.

What could be wrong?

**Comment by AnubisCode** [comment]
same error on windows 10...

**Comment by FlorianBELLAZOUZ** [comment]
Same here on Ubuntu 14

node 9.3 & node carbon (v8.9.3) don't compile
But work fine on node boron (v6.12.2)

**Comment by Dogyunjeong** [comment]
There is no error with node 8.9.3 and npm 5.6.0 on windows 10.

**Comment by dakira** [comment]
@alexhultman I have the same issue. Where is the duplicate that tracks this problem?

**Comment by CoolHandLuke88** [comment]
I ran into this exact issue.
I wanted to leave this here for anyone else that may run into this issue with docker and uws installation.

Hope you guys don't mind I drop this here.

In Dockerfile

FROM node:8.9-alpine

RUN apk add --update \
libc6-compat

Needed libc6-compact

This should resolve the issue seen below.

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

**Comment by FinaOePrs** [comment]
Dear CoolHandluke88, not able to get the solution ur suggesting.
have node 8.10.0 and npm 5.6.0
trying to build sample app from OeCloud

**Comment by dakira** [comment]
@CoolHandLuke88 is experiencing a different issue that happens in Docker containers and is fixed as described. You "fix" this issue by downgrading to an older version of NodeJS. As this as been moved to a place called "garbage-dump" I assume it's out of development. ;)
