### ISSUE TITLE
Rewrite V8 addon / Node.js wrapper

### ISSUE THREAD

**Issue by alexhultman** [uNetworking/bindings#6]
https://github.com/uWebSockets/uWebSockets/issues/381

**Comment by logicoder** [comment]
Maybe [nbind](https://github.com/charto/nbind) could help ?

It's used, for example, in the JS binding of [Facebook Yoga](https://github.com/facebook/yoga/tree/master/javascript) and could probably simplify the development.

It also supports asm.js via Emscripten, which may be a fun thing to test.
