### ISSUE TITLE
Is there closing listener?

### ISSUE THREAD

**Issue by Dogyunjeong** [uNetworking/bindings#65]
Hi.

I want to use uws with Redis for groups message.
could recognize client with 'sec-websocket-key' header.
When socket is closing. I want to remove it from Redis.

the close event just gives me the code and optional string. 
ws seems offer closing event which can still access 'ws' parameter.

Does uws offer similar or compatible methods?

Or is there any way to figure out which user connection is closed?

**Comment by alexhultman** [comment]
You need to figure this out on your own.
