### ISSUE TITLE
Client Tracking

### ISSUE THREAD

**Issue by ohenepee** [uNetworking/bindings#68]
How to do I track clients without increasing memory usage.

```
var sockets = {}
sockets[user.id] = ws
```

The above code increases memory in my case, b'cos `wss.clients` already has all the clients so I'm redoing its work... is there a way to turn off `wss.clients` and thus reduce memory usage... I need a way to send a message to a **particular connected user** after a **different connected user** has performed a specific action. Currently I don't know how else to pull this off without using the code above. Imagine a million users and the RAM usage.

**Comment by alexhultman** [comment]
wss.clients does not require any memory so you're perfectly fine doing what you're doing, or any other similar solution. This is an issue tracker not a personal free support help though.

**Comment by gairom** [comment]
I have similar case and I'm assigning GUID for each user int order to identify it with ws.id = GUID.
I've changed my local version according to my pull request (#62) to return ws when socket is closed so I can get the id of the client.
you can manage it by your own like your code above but you don't have to...
