### ISSUE TITLE
Rebuilding nodejs module fails on Windows

### ISSUE THREAD

**Issue by arximboldi** [uNetworking/bindings#69]
I am building an Electron app that depends on `uws` (via `socket.io`). The `electron-rebuild` command, which tries to rebuild all libraries, fails with the error [1].

This issue has been reported already in `electron-rebuild`, but it arguably belongs here (
https://github.com/electron/electron-rebuild/issues/175)

I have already tried `vcpkg install openssl zlib libuv`, but it did not fix the issue.

This has been tested with `uws 9.14.0`.

Thanks!

**Comment by ras0219-msft** [comment]
Just to check -- are you building for x86 or x64? By default, that vcpkg command will have installed `openssl:x86-windows`, `zlib:x86-windows`, and `libuv:x86-windows`. If you need the 64-bit versions, you'll need to run:
```
>vcpkg install --triplet x64-windows openssl libuv zlib
```

**Comment by alexhultman** [comment]
uws is not an Electron module. Read the FAQ you are about the 100th to ask this. Read the FAQ read the FAQ read the fucking FAQ.
